#!/bin/bash

DISTRO=Armbian_20.11_Odroidxu4_buster_legacy_4.14.204.img.xz

[ -z "${1}" ] && { echo "Usage: $0 [DEVICE] # e.g. /dev/sdc"; exit; }
[ -f ${DISTRO} ] || {
	echo Distro not found. Getting it...
	wget https://mirrors.dotsrc.org/armbian-dl/odroidxu4/archive/${DISTRO}
	echo Done.
}

xz -d - < ${DISTRO} | sudo dd of=${1} bs=4096
sync
