#!/bin/bash
set -x

DISTRO=ubuntu-20.04-5.4-minimal-odroid-xu4-20210112.img.xz

[ -z "${1}" ] && { echo "Usage: $0 [DEVICE] # e.g. /dev/sdc"; exit; }
[ -f ${DISTRO} ] || {
	echo Distro not found.
	exit 1
}

set -x
xz -d - < ${DISTRO} | sudo dd of=${1} bs=4096
sync
