#!/bin/bash

[ -z "$1" ] && { echo "Usage: $0 [DEVICE] # e.g. /dev/sdc1"; exit; }
(cd dat; tar cfz ../dat.tz .)

set -x
sudo mount ${1} /mnt
sync && sleep 1
sudo cp -v dat.tz /mnt/root/
sudo find /mnt/root/
sudo umount /mnt
sync && sleep 1
rm -f *.tz
