#!/bin/bash

[ -f .config ] || {
	read -p "No config found; please edit it before execution (ENTER to continue, CRTL-C to abort):" COMMAND
	cp config .config
	vi .config
	exit
}

source ./.config
cp etc/network/interfaces .interfaces.tmp
sed -i "s/IP_ADDRESS/$IP_ADDRESS/"	.interfaces.tmp
sed -i "s/IP_GATEWAY/$IP_GATEWAY/"	.interfaces.tmp
sed -i "s/IP_DNS/$IP_DNS/"		.interfaces.tmp
sed -i "s/IP_MASK/$IP_MASK/"		.interfaces.tmp

echo
echo /etc/network/interfaces:
sed 's/^/\t/' .interfaces.tmp

set -x
sudo mount ${DEVICE}1 /mnt
sudo cp -v .interfaces.tmp /root/interfaces
sudo umount /mnt
sync
rm -f .*.tmp
